server:
  port: 8002
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:DEPARTMENT_API_DATA;INIT=CREATE SCHEMA IF NOT EXISTS DEPARTMENT_API_DATA
    password:
    username: sa
  application:
    name: department-service
