server:
  port: 8181
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/departments/**
  application:
    name: cloud-gateway
